# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Install the dkms package
  apt:
    name:
      - "dkms"
    state: latest
    update_cache: yes
    install_recommends: no
