# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Install requirements from YUM
  yum:
    name: "{{ yum_packages }}"
    state: latest

- name: Checkout Azure-DCAP-Client git repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_local_dir }}"
    version: "{{ git_repo_branch }}"
    update: yes
    force: yes

- name: Pull prerequisites and setup Makefile
  shell: ./configure
  args:
    chdir: "{{ git_local_dir }}/src/Linux"

- name: Run default Makefile target
  make:
    chdir: "{{ git_local_dir }}/src/Linux"

- name: Run install Makefile target
  make:
    target: install
    chdir: "{{ git_local_dir }}/src/Linux"

- name: Create symlink from /usr/local/lib to /usr/lib64
  file:
    src: /usr/local/lib/libdcap_quoteprov.so
    dest: /usr/lib64/libdcap_quoteprov.so
    force: yes
    state: link

- name: Cleanup installation
  file:
    path: "{{ git_local_dir }}"
    state: absent
